### ISSUE TITLE
Break up into two READMEs, if and switch

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/js-basics-conditionals-readme#1]
break this into two readmes.

**Comment by itzsaga** [comment]
Going through the new JS curriculum for some review and thought the same exact thing.

**Comment by maxwellbenton** [comment]
Hi @aviflombaum and @itzsaga,

Thank you for bringing this to our attention! We have documented this as a known issue and will be reworking this lesson and breaking it into multiple lessons in an upcoming rework of our JavaScript materials. 

Thank you for contributing! 💙
