### ISSUE TITLE
Suggestion for Improvement

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/js-basics-conditionals-readme#2]
There are 2 points that I think would be helpful to note for this lesson: 
1) in the section on block statements, it says: "Block statements return the value of the last evaluated expression." After reading this and starting the first lab after this, I was confused why my function was not returning the return value of a block statement inside. I think it would be helpful to note that a function must explicitly define the return value (you can't just put a block statement inside a function and expect the function to return what the block statement does. 
2) while you are at it, I don't think the course has covered how to define JS functions yet. In the upcoming lab, it asks us to define a few functions and we have not yet been taught how. This would probably be a good opportunity to teach how to define a JS function and then explain my point in #1 above that a block statement will not assign a return value to a function

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials to clarify the difference between implicit returning in block statements vs something like a function where explicitly stating a return is required.  We've also added some content to the control flow lab to introduce writing functions, which should help resolve any confusion.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
