### ISSUE TITLE
break doesn't determine whether a case will be evaluated. It determines if the flow of execution rolls over to the next case

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/js-basics-conditionals-readme#5]
## `break` doesn't determine whether a case will be evaluated. It determines if the flow of execution rolls over to the next case. (Even if the next case would have evaluated to false had it been evaluated.)

From the readme:
>By leaving a `break` at the end of each `case`'s set of statements, we ensure that the `switch` statement will match at most a single `case`. Once it matches the first `case`, it will run that `case`'s statements and then exit. In addition to not accidentally matching multiple `case`s, this also provides a small performance boost because the JavaScript engine doesn't always have to check every single `case`.

`switch` statement will match at most a single `case` even when there are no break statements as demonstrated here:
```javascript

let count = 0;
 
switch (1) {
  case count++:
  // false  // count now equals 1
    console.log('a');
    // not run
    console.log(count);
    // not run

  case count++:
  // true  // count now equals 2
    console.log('b');
    // b
    console.log(count);
    // 2

  case count++:
  // not evaluated becouse a maching case was already found
  // count still equals 2
    console.log('c');
    // c
    console.log(count);
    // 2
}
console.log(count);
// 2
```

Also I'm not sure what performance gains this is referring to as once one case evaluates to true no more cases are evaluated, irrelevant of break statments

What break actually does: ([from mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#Description))

>The optional break statement associated with each case label ensures that the program breaks out of switch once the matched statement is executed and continues execution at the statement following switch. If break is omitted, the program continues execution at the next statement in the switch statement.

Further on in the readme:

>We specified true as the value to switch on. All of our cases are comparisons, and if the comparison returns true its statements will be run. Because we did not include break statements, we allow the JavaScript engine to continue cascading down the cases even if it matches one or more. With age set to 20 in the above example, the first case, age >= 21, returns false and so the assignment of canDrink never happens. The engine then proceeds to the next case, age >= 18, which returns true, assigning the value true to isAdult and canEnlist. **_Since it encounters no break statement, the JavaScript engine then evaluates the final case, age >= 16, which also returns true_**. It assigns true to canVote, reaches the end of the switch statement, and exits.

The final case is run regardless of whether `age >= 16`  it could have been `case false` for the same price. 

from mdn:

>If you forget a break then the script will run from the case where the criterion is met and will run the case after that regardless if criterion was met. See example here:

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing detailed feedback, @arye-dov-eidelman!

We have updated rewritten the switch section of this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
