### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by maxwellbenton** [learn-co-curriculum/js-basics-conditionals-readme#6]
Problem:
This conditionals readme is too long and should be divided into at least two - one for if statements, one for switch as per #1 

Proposal:
Breakdown into multiple Readmes in upcoming rework of JS learn content

**Comment by bkhartmire** [comment]
You have to be 18 years old to vote. This is an error in the NestedConditionals example, which states you can vote in the US at age 16. But for understanding code purposes, the example is good!

**Comment by lizbur10** [comment]
Done for Phase 0
