### ISSUE TITLE
canVote age

### ISSUE THREAD

**Issue by bkhartmire** [learn-co-curriculum/js-basics-conditionals-readme#7]
You have to be 18 years old to vote. But for understanding code purposes, the example is good!
Other examples for rights you have when a US citizen turns 16:
canGetDrivingPermit,
canDriveMoped

**Comment by drakeltheryuujin** [comment]
Hi @bkhartmire,

Thanks for pointing this out, however, in the US, the laws can vary widely by state, even if there are federal laws in place (ex: Cannabis legalization, minors can drink in some states for religious purposes or with adult supervision, etc.) and in New York State, `canGetDrivingPermit` would technically vary from other states too. I will update the language of this exercise for accuracy and to avoid confusion.
