### ISSUE TITLE
No parentheses

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/js-basics-conditionals-readme#8]
In the lesson it states

> If it helps you visualize what's going on, you can wrap the condition, the expressions, or the entire ternary in parentheses:
const age = 17;
const isAdult = age >= 18 ? true : false;
const canWork = age >= 16 ? 1 === 1 : 1 !== 1;
const canEnlist = isAdult ? true : false;
isAdult;
// => false
canWork;
// => true
canEnlist;
// => false

However, where are the parentheses?

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

The materials have been updated and I believe your issue has been resolved. 

Thanks for contributing to the curriculum! 💙
